Algoritmo "AreaRetangulo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Jailson
// Descrição   : Solicitar a base e altura do retangulo
// Autor(a)    : Daniel De Jesus Oliveira
// Data atual  : 28/03/2022
Var
// Seção de Declarações das variáveis 
      base: inteiro
      altura: inteiro
      area: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreval("Digite o valor da base do retangulo")
 Leia(base)
 Escreval("Digite o valor da altura do retângulo")
 Leia(altura)
 area<-base*altura
 Escreval("A area do retângulo é:",area)

Fimalgoritmo