Algoritmo "AreaTriangulo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Jailson
// Descrição   : Solicitar a base e altura do retangulo
// Autor(a)    : Alex
// Data atual  : 28/03/2022
Var
// Seção de Declarações das variáveis 
      base, altura, area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Informe a base do triângulo")
 leia(base)
 escreval("Informe a altura do triângulo")
 leia(altura)
 area<-base * altura / 2
 escreval("A área do triângulo será ", area:5:2)

Fimalgoritmo