Algoritmo "AreaCirculo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Jailson
// Descrição   : Calcular o raio de um circulo
// Autor(a)    : Daniel De Jesus Oliveira
// Data atual  : 28/03/2022
Var
// Seção de Declarações das variáveis 
raio,area,x :real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("Qual é o raio do circulo?")
leia(raio)
x<-raio*3.141592654
escreval ("A área total é:",x)

Fimalgoritmo