Algoritmo "Divisão"
// Disciplina  :  [Logica de Programação com JavaScript]
// Professor   : Jailson Santos
// Descrição   : Solicitar dois valores e exibir o resultado
// Autor(a)    : Daniel De Jesus Oliveira
// Data atual  : 24/03/2022
Var
// Seção de Declarações das variáveis
numero1:real
numero2:real
dividir:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval ("Boa Noite turma do ADS")
Escreval ("Digite Um Número:")
leia(numero1)
Escreval("DIgite um Número:")
leia(numero2)
dividir<-numero1/numero2
Escreval("A divisão dos valores digitados é:",dividir)
Fimalgoritmo