Algoritmo "ExemploDesvioCondicionalSimples"

// Disciplina : [Lógica de Programação e JavaScript]

// Professor : Jailson Costa dos Santos

// Descrição : Aqui você descreve o que o programa faz! (função)

// Autor(a) : Daniel De Jesus Oliveira

// Data atual : 31/03/2022

Var

// Seção de Declarações das variáveis

valor:inteiro



Inicio

// Seção de Comandos, procedimento, funções, operadores

Escreval("Digite um valor:")

Leia(valor)

se valor<10 entao

Escreval("Valor digitado é menor que 10")

fimse

Fimalgoritmo

Leia(numeroCarrosVendidos)

Escreval("Digite o valor ganho por cada carro vendido:")

Leia(valorCarroVendido)

Escreval("Digite o valor de suas vendas mensais:")

Leia(valorTotalVendas)

//Processamento - Calculo



SalarioFinal<-salarioFixo+numeroCarrosVendidos*valorCarroVendido+valorTotalVendas*5/100

//Saída

Escreval("O salário final do vendedor é:",salarioFinal)



Fimalgoritmo