Algoritmo "Sucessor"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Jailson
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Daniel De Jesus Oliveira
// Data atual  : 28/03/2022
Var
// Seção de Declarações das variáveis 
      numero: inteiro
      Sucessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreval("Digite um numero")
 Leia (numero)
 Sucessor <-numero+1
 Escreval("O Sucessor do número digitado é:",Sucessor)

Fimalgoritmo